package playpal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JTable;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author MAHE
 */
public class borrowEquipment extends javax.swing.JFrame {
 int bid;
    /**
     * Creates new form borrowEquipment
     */
    public borrowEquipment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Borrw = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        model = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        borrowid = new javax.swing.JTextField();
        showtabledata = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Equipment Available");

        Borrw.setText("borrow");
        Borrw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrwActionPerformed(evt);
            }
        });

        model.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Equip_id", "Equip_name", "Addressl", "Rent feel", "status"
            }
        ));
        jScrollPane1.setViewportView(model);

        jLabel2.setText("Enter Equipment ID");

        borrowid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowidActionPerformed(evt);
            }
        });

        showtabledata.setText("Show");
        showtabledata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showtabledataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showtabledata)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(borrowid, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(Borrw))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(borrowid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(Borrw))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showtabledata)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Equipments Available");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void borrowidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowidActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_borrowidActionPerformed

    private void showtabledataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showtabledataActionPerformed
        // TODO add your handling code here:
        Connection myConn=null;
        Statement myStmt=null;
        ResultSet myRs= null;
        String user="root";
        String pass="kent";
        try
        {
            myConn= DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/playpal_db", user, pass);
            myStmt=myConn.createStatement();
            String query="select equip_id,EquipName,address,rentamt,status from equipment";
            myRs=myStmt.executeQuery(query);
            //String[] columnNames = {"Equipment id", "Equipment Name", "Address", "Rent Fee","Status"};
            JTable table = new JTable();
            //DefaultTableModel model = ((DefaultTableModel) table.getModel());

            DefaultTableModel model=new DefaultTableModel();
            //model.setColumnIdentifiers(columnNames);
             
             table.setModel(model); 
             

            while(myRs.next())
            {
              
                 model.addRow(new Object[]{myRs.getString("equip_id"), myRs.getString("EquipName"),myRs.getString("address"),
                 myRs.getString("rentamt"),myRs.getString("status")});
                
            }
            
            
            //show message box : "Equipment Added Successfully" 
            
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
        
    }//GEN-LAST:event_showtabledataActionPerformed

    private void BorrwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrwActionPerformed
        // TODO add your handling code here:
         Connection myConn=null;
        Statement myStmt=null;
        ResultSet myRs= null;
        String user="root";
        String pass="kent";
        try{
            myConn= DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/playpal_db", user, pass);
            myStmt=myConn.createStatement();
            bid=Integer.valueOf(borrowid.getText());
            borrowid.setText("");

            System.out.println(bid);
            String query="delete from equipment where equip_id="+bid;
            myStmt.executeUpdate(query);
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
        //LEADS TO PAYMENT PAGE
        
        
    }//GEN-LAST:event_BorrwActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(borrowEquipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(borrowEquipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(borrowEquipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(borrowEquipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new borrowEquipment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Borrw;
    private javax.swing.JTextField borrowid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable model;
    private javax.swing.JButton showtabledata;
    // End of variables declaration//GEN-END:variables
}
