package playpal;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;
import static playpal.dashboard.userid;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MAHE
 */
public class ViewTournament extends javax.swing.JFrame{

    /**
     * Creates new form ViewTournament
     */
    public ViewTournament() {
        Connection myConn = null;
        Statement myStmt = null;
        ResultSet myRs = null;
        int count=0;
        
        String user = "root";
        String pass = "kent";
        
        ActionListener listener = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            if (e.getSource() instanceof JButton){
                String text = ((JButton) e.getSource()).getText();
                
            //JOptionPane.showMessageDialog(null, text.substring(5));
            int result = JOptionPane.showConfirmDialog(null,"Are you sure that you want to participate in "
                    +text.substring(5)+"?", "",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            
            if(result == JOptionPane.YES_OPTION){
               //System.out.print("Yippe");
          try 
           {
                Connection myConn = null;
                Statement myStmt = null;
                ResultSet myRs = null;
                int tour_id=0;
                String tour_name=text.substring(5);
                String user = "root";
                String pass = "kent";
            myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/playpal_db", user, pass);
            myStmt = myConn.createStatement();
            String query1="SELECT tour_id from tournament where tour_name='"+tour_name+"'";
            myRs=myStmt.executeQuery(query1);
            while(myRs.next())
            {
                tour_id=Integer.parseInt(myRs.getString("tour_id"));
                JOptionPane.showMessageDialog(null,"Congrats, your participation is confirmed!");
            }
            myStmt.executeUpdate("INSERT INTO tourn_participation(tour_id,user_id) VALUES("
                        +tour_id+","+userid+")");
            
            
        }
          catch (Exception exc){
            exc.printStackTrace();
        }
               
               
            }
        }
        }
    };
        initComponents();
        String query;
        
        try 
           {
               ResultSet myRs1 = null;
            myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/playpal_db", user, pass);
            myStmt = myConn.createStatement();
            query="SELECT count(tour_id) as c from tournament";
            myRs1=myStmt.executeQuery(query);
            while(myRs1.next())
            {
                count=Integer.parseInt(myRs1.getString("c"));
                
            }
            
            JTextArea tourn[]= new JTextArea[count];
            JButton participate[]= new JButton[count];
            query="SELECT * from tournament;";
            myRs1=myStmt.executeQuery(query);
            int i=0;
            while(myRs1.next())
            {
               String tour_name=myRs1.getString("tour_name");
               tourn[i]= new JTextArea();
               participate[i]=new JButton("JOIN "+tour_name);
               tourn[i].setBounds(10,30+i*170,300,150);
               participate[i].setBounds(350,80+i*170,150,50);
               participate[i].addActionListener(listener);
               this.add(tourn[i]);
               this.add(participate[i]);
               tourn[i].setText(tour_name+ "  ----> "+myRs1.getString("tour_sport")
                + " Tournament\n\nEntry Fee : Rs."+ myRs1.getString("entryFee")+ "\nVenue: "+myRs1.getString("tour_venue")+
                        "\nSchedule: "+myRs1.getString("tour_date")+"\nTimings: "+myRs1.getString("tour_time"));
                tourn[i].setEditable(false);
                i++;
            }
        
            //dispose();
        }
          catch (Exception exc){
            exc.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("TOURNAMENTS LIST");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel1)
                .addContainerGap(234, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(394, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTournament().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
